directories:
  output: release
  buildResources: build
electronVersion: 30.0.1
appId: com.chauhan.erp
productName: Chauhan ERP
mac:
  target: dmg
win:
  target: nsis
linux:
  target: AppImage
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
extraResources:
  - from: ../../node_modules/better-sqlite3
    to: app/node_modules/better-sqlite3
